### PR TITLE
Search rename and order

### PR DESCRIPTION
**Pull request by jerefrer**
Hi there !

For years using Rich in our apps we felt that the file browser would need some searching and ordering capabilities.

Finally I could have both the client need and the time to do it properly and bake it right in Rich itself.
So here it is !

Added features:

* Search bar filtering the items by file name (refresh on keyup with 1s delay)
* Clicking a file name will switch to an input to rename the file. ENTER will submit, ESC and blur will discard changes.
* Two options for sorting the items : "Sort by date, newest first" & "Sort alphabetically"

I took care of making it work with both Paperclip and Carrierwave.

I included I18n translations for English and French for now, others may have to be added.

The style of the file name and the renaming input on grid view mode could be prettier, but it suits us for now. Feel free to make it look awesome !

Here's a demo so you get excited to merge it :)

ezgif com-optimize

### CODE REVIEW

**Comment by iDuuck** [comment]
That's a nice one. Thanks for you effort!

Will merge it into the `master` branch.

**Comment by iDuuck** [comment]
@jerefrer Is it possible to add an updated screenshot to the README?

**Comment by jerefrer** [comment]
@iDuuck Yep I'm on it.

**Comment by jerefrer** [comment]
@iDuuck Ok here are two version, one hovering on a filename to show the renaming feature, and one without. Pick the one you prefer :)

rich-filemanager

rich-filemanager

**Comment by iDuuck** [comment]
Can you do a pull request with the second screenshot?

**Comment by jerefrer** [comment]
@iDuuck See https://github.com/kreativgebiet/rich/pull/205

**Pull request merged**
