### PR TITLE
Update ckeditor up to 4.4.7_full

### PR DESCRIPTION
**Pull request by donbobka**
Due to a lot of bugs with old ckeditor, i decided to update ckeditor. May be it be useful for others.

### CODE REVIEW

**Comment by sponomarev** [comment]
:+1:

**Comment by cec** [comment]
Hi guys! 
Master had broken CKEditor icons and an obsolete version for a long time.
Are there any plans to merge this?

**Comment by sponomarev** [comment]
looks like rich is dead :confused:

**Comment by cec** [comment]
:(
@sponomarev the last merge was 2 months ago, but I'm afraid you are correct :(

Years ago this gem was the best way to include CKEditor in your app, but the official gem definitely picked up the pace.

I find that the best feature of this gem is its refined file upload capabilities, which I cannot give up as the backend of our largest app depends on this.

I believe that the way things are now, this gem should be stripped down to become a set of CKEditor plugins and server-side upload receiver.

In the next week I'll work on it on my fork.

**Comment by iDuuck** [comment]
Hey @cec and @sponomarev,
I am the head maintainer of this gem. Unfortunately my team at @kreativgebiet/development is not able to maintain the gem at the moment due to massive client work. If you are interested in developing and contributing to this gem please feel free do pull requests or tell me that you want to be an active part of the gem and I will give you the contributor role.

**Comment by iDuuck** [comment]
Can anyone tell, if this PR is working for you?

**Comment by sponomarev** [comment]
I use @donbobka  fork for about half a year, and it's completely working

**Comment by cec** [comment]
Hi @iDuuck , 

thanks for letting us know about the status of maintenance, it's nice to see that it's not discontinued.
I really appreciate that you came back to us despite your workload.

Regarding my plan to "reduce" rich to its **awesome-file-upload** features, I personally think that it would be the best choice for everyone:
* maintenance can focus on upload and CKEditor integartion only
* gem users will always have a up-to-date editor, with the little inconvenience of a few more config steps

I'm currently in the process of upgrading our largest web app to Rails4.2. 
Given the tight schedule, if the @donbobka fork works, I believe that it's in the best interest of our compnay that I first use the fork and complete the upgrade.

However, if @iDuuck and your colleagues agree on my point of view, I am definitely up to contribute to this right after being done with the upgrade process and submit a pull request for inspection when ready.

**Comment by iDuuck** [comment]
Thanks for your kind words,@cec.
I am merging this pull request in the evening to be part of the main repository again.

If you want to, I will set you as an contributor after the first pull request!

**Comment by cec** [comment]
Hi @iDuuck ,

sry for the late reply, I was out of order (ill) yesterday.
Does your answer imply that you agree with my idea about reducing the scope of Rich's functionality?

**Comment by iDuuck** [comment]
@cec Yeah, that was my implication. Though, there should be a tag or at least branch that keeps the old features.

**Comment by cec** [comment]
Hi @iDuuck ,

great news! 
I absolutely agree on that.
I saw your merge, I'll update the gem in our app and hurry up as much as I can to get the free time necessary to implement the changes.

Cheers,
cec

**Comment by cec** [comment]
@iDuuck @sponomarev neither the result of this merge nor the branch by @donbobka work for me.

**mediaembed** plugin is not working and crashes the editor (no visible editor).
I removed mediaembed from config.extraPlugins.

But then I get another error from the **lang** plugin, which is missing the **bidi** property.
Strangely enough, if I check the it.js file for lang, I see the bidi property with all expected values.

Did you experience similar issues? At the moment, this is a no-go for me :(

**Comment by iDuuck** [comment]
Wow, thought it was working. Will revert if I have time

**Comment by cec** [comment]
@iDuuck well let's just wait for their reply to find out if it's my own issue, although I'm not sure where to look since I'm getting the problem with vanilla configs...

**Comment by cec** [comment]
Hi @iDuuck ,

today I had time to verify this again. The PR **is definitely working and legit**.

For some reason, `rake tmp:clear && rake assets:clean` was leaving some stale files under public/assets  that I had to remove manually (odd enough, but whatever).

With the new version of CKEditor, a plugin was renamed: `MediaEmbed => mediaembed`

The button name for the toolbar is still MediaEmbed, thus most people won't notice the change.
In my app, I had to override the plugin for some custom functionality. 
Anybody overriding the plugin might have to update their overriding solution appropriately.

I suggest the realease of a new version on rubygems.

I hope to send a PR soon with my changes to Rich.
Have a nice week!

**Pull request merged**
