### PR TITLE
Fixed undefined method 'rich_file='

### PR DESCRIPTION
**Pull request by Ammet**
With new commits

### CODE REVIEW

**Comment by iduuck** [comment]
Is it working on both, Paperclip and Carrierwave?

**Comment by Ammet** [comment]
Not tested for Carrierwave.

**Comment by iduuck** [comment]
Is it possible that you test this with Carrierwave? Because I think the
`include Backends::PaperClip` will bomb CarrierWave support.

**Comment by jdejong** [comment]
FYI if you want to fix this in an existing code base you can use the following code in an initializer

```
module Rich
  class RichFile < ActiveRecord::Base
    include Backends::Paperclip
  end

  module Backends
    module Paperclip
      Rich::RichFile.send(:include, Backends::Paperclip)
    end
  end
end
```

**Pull request closed without merging**
